### ISSUE TITLE
Data Pipeline - Microsoft Azure Managed Services Support

### ISSUE THREAD

**Issue by jillurquddus** [hyperlearningai/ontopop#1]
### Task Summary
Provide tested support for relevant Microsoft Azure managed services as part of the OntoPop data pipeline.

## Task Description
Provide tested support for relevant Microsoft Azure managed services as part of the OntoPop data pipeline, as per the subtask list below. Rather than developing platform-specific integration services, use the Spring Framework to test existing services when deployed to the Microsoft Azure cloud computing platform, and make use of Spring Azure modules where appropriate. The use of platform-specific SDKs should be minimised as far as possible to promote interoperability and reusability.

## Subtask List

**Compute**

- [ ] 1. Ontology Ingestion - [Spring Cloud Function](https://spring.io/projects/spring-cloud-function) deployed to an [Azure Function](https://azure.microsoft.com/en-gb/services/functions/) app
- [ ] 2. Ontology Validation - [Spring Cloud Function](https://spring.io/projects/spring-cloud-function) deployed to an [Azure Function](https://azure.microsoft.com/en-gb/services/functions/) app
- [ ] 3. Ontology Triplestore Loading - [Spring Cloud Function](https://spring.io/projects/spring-cloud-function) deployed to an [Azure Function](https://azure.microsoft.com/en-gb/services/functions/) app
- [ ] 4. Ontology Parsing - [Spring Cloud Function](https://spring.io/projects/spring-cloud-function) deployed to an [Azure Function](https://azure.microsoft.com/en-gb/services/functions/) app
- [ ] 5. Ontology Modelling - [Spring Cloud Function](https://spring.io/projects/spring-cloud-function) deployed to an [Azure Function](https://azure.microsoft.com/en-gb/services/functions/) app
- [ ] 6. Ontology Graph Loading - [Spring Cloud Function](https://spring.io/projects/spring-cloud-function) deployed to an [Azure Function](https://azure.microsoft.com/en-gb/services/functions/) app
- [ ] 7. Ontology Graph Indexing - [Spring Cloud Function](https://spring.io/projects/spring-cloud-function) deployed to an [Azure Function](https://azure.microsoft.com/en-gb/services/functions/) app

**Storage**

- [ ] Object Storage - [Azure BLOB Storage](https://azure.microsoft.com/en-gb/services/storage/blobs/)
- [ ] RDBMS - [Azure SQL](https://azure.microsoft.com/en-gb/products/azure-sql/database/) and/or Azure managed PostgreSQL/MySQL/MariaDB
- [ ] Graph Database -[ Azure Cosmos DB](https://azure.microsoft.com/en-gb/services/cosmos-db/) (Gremlin API)
- [ ] Search Index - [Azure Cognitive Search](https://azure.microsoft.com/en-gb/services/search/#overview)

**Integration**

- [ ] Messaging - [Azure Service Bus](https://azure.microsoft.com/en-gb/services/service-bus/)

**Security**

- [ ] Secrets - [Azure Key Vault](https://azure.microsoft.com/en-gb/services/key-vault/)

## Acceptance Criteria

See each subtask for acceptance criteria.
